/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as VerifiedActivityRouteImport } from './routes/verified-activity'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifiedActivityRoute = VerifiedActivityRouteImport.update({
  id: '/verified-activity',
  path: '/verified-activity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRoute
  '/passport': typeof PassportRoute
  '/transactions': typeof TransactionsRoute
  '/verified-activity': typeof VerifiedActivityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRoute
  '/passport': typeof PassportRoute
  '/transactions': typeof TransactionsRoute
  '/verified-activity': typeof VerifiedActivityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRoute
  '/passport': typeof PassportRoute
  '/transactions': typeof TransactionsRoute
  '/verified-activity': typeof VerifiedActivityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/inventory' | '/passport' | '/transactions' | '/verified-activity'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inventory' | '/passport' | '/transactions' | '/verified-activity'
  id:
    | '__root__'
    | '/'
    | '/inventory'
    | '/passport'
    | '/transactions'
    | '/verified-activity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InventoryRoute: typeof InventoryRoute
  PassportRoute: typeof PassportRoute
  TransactionsRoute: typeof TransactionsRoute
  VerifiedActivityRoute: typeof VerifiedActivityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verified-activity': {
      id: '/verified-activity'
      path: '/verified-activity'
      fullPath: '/verified-activity'
      preLoaderRoute: typeof VerifiedActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InventoryRoute: InventoryRoute,
  PassportRoute: PassportRoute,
  TransactionsRoute: TransactionsRoute,
  VerifiedActivityRoute: VerifiedActivityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
