/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DispenseRouteImport } from './routes/dispense'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as PrescribeRouteImport } from './routes/prescribe'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as VerifiedActivityRouteImport } from './routes/verified-activity'
import { Route as WalletRouteImport } from './routes/wallet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DispenseRoute = DispenseRouteImport.update({
  id: '/dispense',
  path: '/dispense',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescribeRoute = PrescribeRouteImport.update({
  id: '/prescribe',
  path: '/prescribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifiedActivityRoute = VerifiedActivityRouteImport.update({
  id: '/verified-activity',
  path: '/verified-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dispense': typeof DispenseRoute
  '/inventory': typeof InventoryRoute
  '/passport': typeof PassportRoute
  '/prescribe': typeof PrescribeRoute
  '/transactions': typeof TransactionsRoute
  '/verified-activity': typeof VerifiedActivityRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dispense': typeof DispenseRoute
  '/inventory': typeof InventoryRoute
  '/passport': typeof PassportRoute
  '/prescribe': typeof PrescribeRoute
  '/transactions': typeof TransactionsRoute
  '/verified-activity': typeof VerifiedActivityRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dispense': typeof DispenseRoute
  '/inventory': typeof InventoryRoute
  '/passport': typeof PassportRoute
  '/prescribe': typeof PrescribeRoute
  '/transactions': typeof TransactionsRoute
  '/verified-activity': typeof VerifiedActivityRoute
  '/wallet': typeof WalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dispense'
    | '/inventory'
    | '/passport'
    | '/prescribe'
    | '/transactions'
    | '/verified-activity'
    | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dispense'
    | '/inventory'
    | '/passport'
    | '/prescribe'
    | '/transactions'
    | '/verified-activity'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/dispense'
    | '/inventory'
    | '/passport'
    | '/prescribe'
    | '/transactions'
    | '/verified-activity'
    | '/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DispenseRoute: typeof DispenseRoute
  InventoryRoute: typeof InventoryRoute
  PassportRoute: typeof PassportRoute
  PrescribeRoute: typeof PrescribeRoute
  TransactionsRoute: typeof TransactionsRoute
  VerifiedActivityRoute: typeof VerifiedActivityRoute
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispense': {
      id: '/dispense'
      path: '/dispense'
      fullPath: '/dispense'
      preLoaderRoute: typeof DispenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescribe': {
      id: '/prescribe'
      path: '/prescribe'
      fullPath: '/prescribe'
      preLoaderRoute: typeof PrescribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verified-activity': {
      id: '/verified-activity'
      path: '/verified-activity'
      fullPath: '/verified-activity'
      preLoaderRoute: typeof VerifiedActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DispenseRoute: DispenseRoute,
  InventoryRoute: InventoryRoute,
  PassportRoute: PassportRoute,
  PrescribeRoute: PrescribeRoute,
  TransactionsRoute: TransactionsRoute,
  VerifiedActivityRoute: VerifiedActivityRoute,
  WalletRoute: WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
